[general]
import = [
	"~/.config/alacritty/themes/chicago95.toml"
]
[window]
title = "Alacritty"
dynamic_title = false
padding.x = 20
padding.y = 20
decorations = "Full"
[cursor]
style = { shape = "underline", blinking = "Always"}
[font]
size = 10

